# Generated by Django 4.2 on 2023-04-12 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0003_orderprodukitem_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='produkItem',
            new_name='produkItems',
        ),
    ]
