# Generated by Django 4.2 on 2023-04-12 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0004_rename_produkitem_order_produkitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderprodukitem',
            old_name='produkItem',
            new_name='produk_item',
        ),
    ]
