# Generated by Django 4.2 on 2023-06-04 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0009_kategori_alter_produkitem_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategori',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
