# Generated by Django 4.2 on 2023-06-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0010_alter_kategori_slug_alter_produkitem_label_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produkreview',
            name='ratting',
        ),
        migrations.AddField(
            model_name='produkreview',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
