# Generated by Django 4.2 on 2023-06-04 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0011_remove_produkreview_ratting_produkreview_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produkreview',
            old_name='produk_item',
            new_name='produk',
        ),
        migrations.RemoveField(
            model_name='produkreview',
            name='waktu',
        ),
        migrations.AlterField(
            model_name='produkreview',
            name='komentar',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='produkreview',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=2),
        ),
    ]
