# Generated by Django 4.2 on 2023-06-05 01:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('toko', '0014_rename_name_produkreview_nama'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProdukReview',
            new_name='Comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='komentar',
            new_name='konten',
        ),
    ]
