# Generated by Django 4.2 on 2023-06-05 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0015_rename_produkreview_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='produk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='toko.produkitem'),
        ),
    ]
