# Generated by Django 4.2 on 2023-06-05 04:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('toko', '0016_alter_comment_produk'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='ProdukReview',
        ),
        migrations.RenameField(
            model_name='produkreview',
            old_name='konten',
            new_name='komentar',
        ),
    ]
