# Generated by Django 4.2 on 2023-06-05 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0017_rename_comment_produkreview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkreview',
            name='produk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='toko.produkitem'),
        ),
    ]
