# Generated by Django 4.2 on 2023-06-05 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0018_alter_produkreview_produk'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdukImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.ImageField(upload_to='product_pics')),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toko.produkitem')),
            ],
        ),
    ]
