# Generated by Django 4.2 on 2023-06-05 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0019_produkimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produkimages',
            options={'verbose_name_plural': 'Product Images'},
        ),
        migrations.AlterField(
            model_name='produkimages',
            name='produk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_images', to='toko.produkitem'),
        ),
    ]
