# Generated by Django 4.2 on 2023-06-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0020_alter_produkimages_options_alter_produkimages_produk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produkimages',
            name='gambar',
        ),
        migrations.AddField(
            model_name='produkimages',
            name='images',
            field=models.ImageField(default='product.jpg', upload_to='product-images'),
        ),
    ]
