# Generated by Django 4.2 on 2023-06-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0021_remove_produkimages_gambar_produkimages_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkitem',
            name='detail_produk',
            field=models.TextField(null=True),
        ),
    ]
