# Generated by Django 4.2 on 2023-06-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0023_alter_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='produkitem',
            name='harga',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='produkitem',
            name='harga_diskon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
