# Generated by Django 4.2 on 2023-06-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0023_alter_payment_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produkimages',
            options={'verbose_name_plural': 'Gambar Produk'},
        ),
        migrations.AlterField(
            model_name='produkimages',
            name='images',
            field=models.ImageField(default='produk.jpg', upload_to='product-images'),
        ),
    ]
