# Generated by Django 4.2 on 2023-06-07 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0010_alter_kategori_slug'),
        ('toko', '0010_produkitem_detail_produk_alter_kategori_slug_and_more'),
        ('toko', '0024_alter_payment_amount_alter_produkitem_harga_and_more'),
    ]

    operations = [
    ]
