# Generated by Django 4.2 on 2023-06-07 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0024_alter_produkimages_options_alter_produkimages_images'),
        ('toko', '0026_alter_produkitem_harga_alter_produkitem_harga_diskon'),
    ]

    operations = [
    ]
