# Generated by Django 4.2 on 2023-06-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0028_kontak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkreview',
            name='nama',
            field=models.CharField(max_length=50),
        ),
    ]
