# Generated by Django 4.2 on 2023-06-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0029_alter_produkreview_nama'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kategori',
        ),
        migrations.AlterField(
            model_name='produkitem',
            name='kategori',
            field=models.CharField(choices=[('pakaian', 'Pakaian'), ('sepatu', 'Sepatu'), ('tas', 'Tas'), ('aksesoris', 'Aksesoris')], max_length=9),
        ),
    ]
