# Generated by Django 4.2 on 2023-06-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0030_delete_kategori_alter_produkitem_kategori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkitem',
            name='kategori',
            field=models.CharField(choices=[('P', 'Pakaian'), ('S', 'Sepatu'), ('A', 'Tas'), ('T', 'Aksesoris')], max_length=9),
        ),
    ]
